# Generated by Django 4.0.3 on 2024-04-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_movie_title_alter_movie_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
