# Generated by Django 4.0.3 on 2024-05-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movie_isseries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CO2',
        ),
    ]
