# Generated by Django 5.0.4 on 2024-04-06 06:46

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('mystery', 'Mystery'), ('comedy', 'Comedy')], default='No genre available', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_carousel_card',
            field=models.ImageField(default='media/images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_feature_cover',
            field=models.FileField(default='media/images/default_image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='playback',
            field=models.FileField(default='media/images/default_image.png', upload_to='playback/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
