# Generated by Django 5.0.4 on 2024-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movie_image_carousel_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(default='movie/The_Internship_Official_Trailer_2_2013_-_Vince_Vaughn_Owen_Wilson_Comedy_HD_TC2M1y7.mp4', upload_to='movie/'),
        ),
    ]
