# Generated by Django 5.0.4 on 2024-04-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mymovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymovies',
            old_name='user_movies',
            new_name='user',
        ),
    ]
