# Generated by Django 5.0.4 on 2024-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_movies_mymovies_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(default='movie/65aaa30f-af07-4968-a1b0-c107bc902b90.mp4', upload_to='movie/'),
        ),
    ]
